### PR TITLE
fix: do not define filename as string literal

### PR DESCRIPTION
**Pull request by matteo-cristino**
String literal are seaved as read only data

### CODE REVIEW

**Comment by jaromil** [comment]
Oh wow!!! you fixed a lot

**Comment by matteo-cristino** [comment]
Almost there 🤞

**Comment by matteo-cristino** [comment]
Remaining problems:
* `rm_ftw` breaks on removing directories and results in 
```
Error: remove path C:\Users\RUNNER~1\AppData\Local\Temp\CJIT-UAWstjjzLyowjyeG/sec_api
Permission denied
Error: nftw path C:\Users\RUNNER~1\AppData\Local\Temp\CJIT-UAWstjjzLyowjyeG
Permission denied
```
* `cjit` is terminated before the code execution ends, for example the output of `hello.c` is
```
CJIT 
Source to execute: test\hello.c
Loading source file test\hello.c
Compilation successful
Execution start
---
---
Execution completed
Hello World!
```

**Comment by matteo-cristino** [comment]
Since the print of output in the correct order seems to not have a quick solution, will create a issue and work on it on another PR to avoid having conflicts in this PR that already fixes quite some window problems

**Comment by jaromil** [comment]
awesome!!!!! you rock

**Pull request merged**
